# Generated by Django 2.0 on 2018-01-18 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True)),
                ('in_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Nic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=100)),
                ('slot', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('data_center', models.CharField(blank=True, max_length=100)),
                ('ip', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True)),
                ('subnet', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True)),
                ('gateway', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='nic',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nics', to='basic.Server'),
        ),
        migrations.AddField(
            model_name='ippool',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='basic.Server'),
        ),
    ]
