# Generated by Django 2.0 on 2018-01-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_auto_20180118_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.CharField(blank=True, choices=[('BLK', 'Black'), ('BLU', 'Blue'), ('RED', 'Red'), ('PURPL', 'PURPLER'), ('GRN', 'GREEN'), ('WHT', 'WHITE')], default=('WHT', 'WHITE'), max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default=('S', 'SMALL'), max_length=20),
        ),
    ]
