# Generated by Django 2.0 on 2018-01-06 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='highest_education',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('High School', 'High School'), ('Post Grad', 'Post Grad'), ('Poly', 'Poly')], default='NA', max_length=5),
        ),
    ]
