# Generated by Django 2.0 on 2018-01-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_auto_20180106_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='highest_education',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('High School', 'High School'), ('Post Grad', 'Post Grad'), ('Poly', 'Poly')], default='NA', max_length=100),
        ),
    ]
